# Generated by Django 3.0.4 on 2020-06-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='XRaySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('diseaselist_dict', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='samplexray.Dictionary')),
                ('userperson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=240)),
                ('value', models.CharField(max_length=240)),
                ('container', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='samplexray.Dictionary')),
            ],
        ),
    ]
