# Generated by Django 3.0.4 on 2020-05-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xraysample',
            name='slug',
        ),
    ]
