# Generated by Django 3.0.4 on 2020-05-31 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samplexray', '0002_remove_xraysample_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='xraysample',
            name='userperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
