# Generated by Django 3.0.4 on 2020-06-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0002_auto_20200602_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xraysample',
            name='diseaselist_dict',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='samplexray.Dictionary'),
        ),
    ]
