# Generated by Django 3.0.4 on 2020-06-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0003_auto_20200602_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluepair',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samplexray.Dictionary'),
        ),
        migrations.AlterField(
            model_name='xraysample',
            name='diseaselist_dict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samplexray.Dictionary'),
        ),
    ]
