# Generated by Django 3.0.4 on 2020-06-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0004_auto_20200602_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xraysample',
            name='diseaselist_dict',
        ),
    ]
