# Generated by Django 3.0.4 on 2020-06-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0006_auto_20200602_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xraysample',
            old_name='cool',
            new_name='atelectasis',
        ),
        migrations.RenameField(
            model_name='xraysample',
            old_name='fist',
            new_name='cardiomegaly',
        ),
        migrations.RenameField(
            model_name='xraysample',
            old_name='ok',
            new_name='consolidation',
        ),
        migrations.RenameField(
            model_name='xraysample',
            old_name='stop',
            new_name='edema',
        ),
        migrations.RenameField(
            model_name='xraysample',
            old_name='yo',
            new_name='pleural_effusion',
        ),
    ]
