# Generated by Django 3.0.4 on 2020-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplexray', '0007_auto_20200618_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='xraysample',
            name='heatmap_image',
            field=models.ImageField(blank=True, upload_to='heatmaps/'),
        ),
    ]
